### ISSUE TITLE
Test suite fails with crashes when using report callback from the extension

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/psautohint#118]
Currently we force the glyph analysis functionality to go through `autohintexe`, because using the C extension causes crashes randomly in the test suite. I tried to debug this, and it looks like a memory corruption somewhere or overzealous optimization caused by Undefined Behaviour, but none of the debugging tools I used found anything that helps here (valgrind, `-fsanitize=address`, `-fsanitize=undefined`).

**Comment by anthrotype** [comment]
maybe duplicate as https://github.com/adobe-type-tools/psautohint/issues/103 ?

**Comment by khaledhosny** [comment]
Possibly, but I’m not sure. I get the crashes even with all optimizations disabled.

**Comment by anthrotype** [comment]
ah.. so it's not that. unless something has changed since I opened that issue, which causes crashes even without optimizations

**Comment by miguelsousa** [comment]
@cjchapman is hoping to fix this with the changes at #195.

**Comment by josh-hadley** [comment]
@khaledhosny can you comment on whether this is still an issue, and if so, can you provide some additional details on how to reproduce it?

**Comment by khaledhosny** [comment]
I can’t test right now, but you can check the cases where we default `use_autohintexe` to `True`, make it `False` and see if anything still breaks.
