### ISSUE TITLE
Some outlines are modified when using --reference-font

### ISSUE THREAD

**Issue by madig** [adobe-type-tools/psautohint#122]
Using `-r` to hint compatibly results in some modified outlines in the non-reference masters. This prevents building a variable font.

1. `curl -O https://raw.githubusercontent.com/madig/cantarell-fonts/master/src/Cantarell.glyphs`
2. `fontmake -g Cantarell.glyphs -o otf --keep-overlaps`
3. Look at e.g. the brevecomb in uni1EAE in all masters, they should be compatible.
4. `psautohint -r master_otf/Cantarell-Regular.otf master_otf/Cantarell-Bold.otf master_otf/Cantarell-Light.otf`
5. Check again. The path is as it should be in Regular but modified in Light and Bold.

**Comment by khaledhosny** [comment]
Looks like a memory issue, here I get:
```
double free or corruption (!prev)
Aborted (core dumped)
```

Investigating.
