### ISSUE TITLE
Change name of the processed layer

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/psautohint#124]
Normalizing a UFO3 font whose **layercontents.plist** file contains these strings,

```xml
    <array>
      <string>AFDKO ProcessedGlyphs</string>
      <string>glyphs.com.adobe.type.processedGlyphs</string>
    </array>
```

will change the second string (and the directory name) to `glyphs.A_F_D_K_O_ P_rocessedG_lyphs`.

Ran into this problem while working on transitioning **makeinstancesufo**  from using autohint to using psautohint.

The change I made on the afdko repo was to use `com.adobe.type.processedglyphs` for the name of the layer. See https://github.com/adobe-type-tools/afdko/pull/662/commits/ea1f41b966246d9df618f7fb393f44ab8a0de97c

To rename the directories in the test results from **glyphs.com.adobe.type.processedGlyphs** to **glyphs.com.adobe.type.processedglyphs** I had to use `git mv`.

**Comment by anthrotype** [comment]
who normalized it that way?
the layer directory names only must start with `glyphs.` and be unique, they can be arbitrary otherwise.

**Comment by anthrotype** [comment]
ah the ufonormalizer is using the UFO3 user name to file name conventions to normalize the layer directory names. 

https://github.com/unified-font-object/ufoNormalizer/blob/4365ad6eece07da5ddc4e9a7100036ac5548efe8/src/ufonormalizer.py#L264

your directory contained an uppercase and thus it was changed.. ok.

**Comment by khaledhosny** [comment]
I ran into this several times while porting to ufoLib and had to jump through hoops to keep ufoLib from changing directory name. Oh well… UFO, the gift that keeps on giving.
