### ISSUE TITLE
port to use fontTools.ufoLib

### ISSUE THREAD

**Issue by anthrotype** [adobe-type-tools/psautohint#126]
basically, all the ufoLib imports will need to be changed to equivalent ones from fontTools.ufoLib, and then in install_requires we can drop standalone ufoLib, and replace it with fonttools[ufo] >= 3.32.0, possibly fonttools[ufo,lxml] if you want faster XML

**Comment by anthrotype** [comment]
the pointPen module was moved to `fontTools.pens.pointPen`

**Comment by khaledhosny** [comment]
I’m waiting for FontTools to provide a better API. The `ufoLib` API was PITA to work with (especially the reader/writer split) and I’d rather not touch it again.
