### ISSUE TITLE
CLI: `-o` parameter order dependant

### ISSUE THREAD

**Issue by madig** [adobe-type-tools/psautohint#129]
psautohint errors out when I invoke it like `psautohint -o output.otf input.otf` but works fine if I do `psautohint input.otf -o output.otf`.

```
> .\venv\Scripts\psautohint -o .\build\desktop\asdf_Bd.otf .\build\unhinted\asdf_Bd.otf
usage: psautohint [-h] [-v] [-o PATH [PATH ...]] [-r PATH] [-a] [-w]
                  [-g GLYPH_LIST | --glyphs-file PATH | -x GLYPH_LIST | --exclude-glyphs-file PATH]
                  [-c | --report-only] [--log PATH] [-d] [--no-flex]
                  [--no-hint-sub] [--no-zones-stems] [--fontinfo-file PATH]
                  [--print-dflt-fddict] [--print-list-fddict] [--doc-fddict]
                  [--info] [--version]
                  FONT [FONT ...]
psautohint: error: the following arguments are required: FONT
```

Edit: just saw that `-o` is greedy. Hm...

**Comment by josh-hadley** [comment]
Looking over the code, it appears that `psautohint` was set up to accept a parallel set of inputs and outputs, i.e.:
`psautohint path/to/input1 /path/to/input2 -o /path/to/output1 /path/to/output2`

Which works, but as a user it strikes me as unintuitive. @khaledhosny or @miguelsousa any thoughts on this as to why it was implemented this way? @madig's case that fails (`psautohint -o output.otf input.otf`) seems like it would be a pretty common use case and user expectation but maybe I have missed the discussion on the development of this scheme.

**Comment by miguelsousa** [comment]
I agree that having to place the `-o` option at the end is unintuitive.
I think we have two options:
1. fix the `-o` option so it works intuitively for any number of files, or
2. revert the `-o` to only support one file

**Comment by khaledhosny** [comment]
The multiple input and output files are for compatible (AKA multiple master) hinting. The number of output files must match the number of input files, or we can’t support an -o option at all. The fixed order of the arguments is not intentional, it is probably a side effect of the way it checks for the number of input files.

**Comment by josh-hadley** [comment]
Using ` -- ` after the path[s] for `-o` seems to work with current psautohint (v1.9.4):
`psautohint -o out/output.otf -- input.otf`
`psautohint -o out/output0.otf out/output1.otf -- input0.otf input1.otf`

@miguelsousa , @madig is that a reasonable way to proceed (without modifying psautohint)?

**Comment by miguelsousa** [comment]
Still not intuitive, so I'd say it's not a good solution.

**Comment by madig** [comment]
FWIW, I am also ok with leaving things are they are currently, unless someone finds a way to get `argparse` to do what is intuitive.

**Comment by josh-hadley** [comment]
I think @miguelsousa and I have found a way. Testing now, stay tuned for a PR.
