### ISSUE TITLE
“Conflicts with current hints” for unhinted source files

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/psautohint#149]
When I run `makeinstancesufo -d test.designspace` in the attached project, I get the following output:
```
ERROR:_psautohint:comma.sups:   Conflicts with current hints: 0 527 0 507 b.
ERROR:_psautohint:comma.sups:   Conflicts with current hints: 0 439 0 527 b.
ERROR:_psautohint:comma.sups:   Conflicts with current hints: 0 527 0 507 b.
ERROR:_psautohint:comma.sups:   Conflicts with current hints: 0 439 0 527 b.
```

This is peculiar, because there are no previously-existing hints.
[psautohint_test.zip](https://github.com/adobe-type-tools/psautohint/files/2954000/psautohint_test.zip)

**Comment by khaledhosny** [comment]
I think the wording is a bit confusing; it is reporting a conflict between a previously added hint during this hinting run, not a hint read from the font (as a matter of fact, we don’t read existing hinting from UFO fonts).

**Comment by miguelsousa** [comment]
Does it need to be reported? If yes, should it be a warning rather than an error?

**Comment by frankrolf** [comment]
Yes, I was a bit confused by it. What is the user action supposed to be after such a message?

**Comment by khaledhosny** [comment]
I guess it should be a warning (these new errors came from re-working and unifying the logging system, so previously they were either suppressed or shown under some conditions that we now lost).

**Comment by miguelsousa** [comment]
They seem like messages for someone that wants to know in detail what's going on behind the scenes, so I'd argue that there's little value in exposing them to users.

**Comment by khaledhosny** [comment]
DEBUG then, that is our grab bag for messages that no one should want to use.

**Comment by miguelsousa** [comment]
SGTM

**Comment by kontur** [comment]
Found this same "error" message confusing a few times and while I have no idea about anything C I figured this would be an easy fix. 

I changed the `LOGERROR` to `LOGDEBUG` in the [source](https://github.com/adobe-type-tools/psautohint/blob/master/libpsautohint/src/report.c#L381) and followed the README to "build the C extension", and "build just the `autohintexe` binary", respectively, but the same Error traces are still being output.

What am I missing to get the change in the src to show up when running the CLI command?

**Comment by josh-hadley** [comment]
@kontur I was able to see the results of a change locally by doing the following:
1) uninstall any current psautohint (`pip uninstall psautohint` and/or manually delete from `site-packages`)
2) delete `build` or `dist` folders in psautohint
3) `python setup.py install`

**Comment by kontur** [comment]
Ah, thanks, it seems the `rm -r build` is necessary for the change to take effect.
