### ISSUE TITLE
Problem in setup.py

### ISSUE THREAD

**Issue by schriftgestalt** [adobe-type-tools/psautohint#156]
if I clone a fresh repo and try to run `python setup.py build`, I get this:
```
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    from setuptools.command.build_clib import build_clib as _build_clib
ImportError: No module named build_clib
```
Commenting out this line and the class `CustomBuildClib`(starting line 394) the setup process goes through and I can build in Xcode again.

**Comment by anthrotype** [comment]
Please pip install —upgrade setuptools and try again

**Comment by schriftgestalt** [comment]
It works with python3. Sorry for noise (setuptools requires six 1.10 and the version in 2.7 from the system can’t be upgraded (at least not through pip). This build is not possible under python 2.

**Comment by anthrotype** [comment]
You should be able to pip install —upgrade —user setuptools, even with the Mac system python2.7.
Or even better, use virtualenv.

**Comment by anthrotype** [comment]
> This build is not possible under python 2.
 
No, it is possible. See the precompiled wheel that is uploaded to PyPI 
https://pypi.org/project/psautohint/#files
