### ISSUE TITLE
[psautohint] has opinions on what’s bogus

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/psautohint#159]
`WARNING: threeemdash: Glyph bounding box looks bogus: 40 235 2230 261.`

Perhaps `psautohint` could check against a list of code points for known-wide glyphs before emitting this message? What’s “bogus” (where is the threshold)?

**Comment by frankrolf** [comment]
Transferred the issue, sorry about that.

**Comment by josh-hadley** [comment]
This is where the opinion is formed: https://github.com/adobe-type-tools/psautohint/blob/b2c426fd31ee3a7379ec525f439252e3bd3e099c/libpsautohint/src/bbox.c#L357-L358

I guess the routine could be updated to print out which coordinate exceeds the limit, something like:
`WARNING: threeemdash: Glyph bounding box looks bogus: 40 235 2230 261 (upper-right X > 1600)`

But, thinking about it, I don't really care for calling it "bogus", and those limits seem kinda low...could we re-evaluate the whole thing (values and messaging)?

**Comment by typoman** [comment]
I get this too, the glyph is a ligature which is wider than normal glyphs:
```
WARNING:_psautohint:arSeenPF.m_arYehFARPF.f.liga: Glyph bounding box looks bogus: 50 -210 1683 440.
WARNING:_psautohint:arSheenPF.m_arYehFARPF.f.liga: Glyph bounding box looks bogus: 50 -210 1683 767.
WARNING:_psautohint:arSeenYehPF.f: Glyph bounding box looks bogus: 50 -412 1683 440.
```

**Comment by frankrolf** [comment]
What @typoman didn’t mention here is that he actually gets hundreds of lines of “bogus” output. All that only because he works on an Arabic font, which has wider glyphs in general.

**Comment by josh-hadley** [comment]
Indeed, that could probably get very annoying. My vote is to keep the warning in place, but raise the limits (significantly).

**Comment by frankrolf** [comment]
I would really appreciate if this warning would vanish behind the `--verbose` flag (if not removed completely). Thank you!
