### ISSUE TITLE
Problem in how HashPointPen hashes the component's transformation

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/psautohint#165]
`HashPointPen` only captures transformation values when they differ from the default values.

```python
            if transformation[i] != self.DEFAULT_TRANSFORM[i]:
                self.data.append(str(round(v, 9)))
```

This is a problem because it leads to the creation of the same hash for glyphs that are visually different, and in certain circumstances it will lead to not detecting changes in particular glyphs. Consider the following example (font attached).

Glyph named **before** is a composite summarily defined as,
```xml
<component base="a" yOffset="200"/>
```
and glyph named **after** is a composite summarily defined as,
```xml
<component base="a" xOffset="200"/>
```
The only difference between them is **X** vs. **Y** offset.

The hash generated by `HashPointPen` will be the same for both glyphs. If this kind of change were to happen on the same glyph, the alteration from one version (before state) to another (after state) will be unnoticed by the tools paying attention to the `processedHashMap` file, thus leading to outdated glyphs in the UFO's processed layer.

[hashmap_transform.ufo.zip](https://github.com/adobe-type-tools/psautohint/files/3235796/hashmap_transform.ufo.zip)

**Comment by khaledhosny** [comment]
I think I was trying to replicate the behavior of old code, so if the old code behaves differently here then that is my bug and we should fix `HashPointPen` to match it, if not then we need to think of a solution. Either check the transformation values in a fixed order, or prefix the values with unique key for each type, e.g. `x200`, `y200`, `sx200`, `sy200` instead of just `200` or something like that.

**Comment by miguelsousa** [comment]
The old code has the same problem, and `HashPointPen` matches it **if the glif file is normalized**.

I think storing just the values (including the defaults) should be enough to fix this.

**Comment by khaledhosny** [comment]
OK, would the order matter? (Not sure if `enumerate(transformation)` is guaranteed to always give the same order.)

**Comment by miguelsousa** [comment]
It does matter. `transformation` has a fixed order.

**Comment by miguelsousa** [comment]
working on a PR
