### ISSUE TITLE
Should option 'write-to-default-layer' delete the processed layer?

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/psautohint#171]
@frankrolf @khaledhosny 

Consider this scenario:
1. **psautohint** is run on a UFO font for the first time, no options are used
2. The font is worked on; the glyphs in the foreground/default layer are modified
3. **psautohint** is run on the font again, but this time the option `--write-to-default-layer` is used

In step 1, psautohint adds a processed layer to the UFO.
Shouldn't that layer be deleted in step 3?

I think it should, because when building the OTF **makeotf** gives preference to the outlines in the processed layer, however in this scenario those are not guaranteed to be the latest version. 
Deleting the processed layer would also solve some complications involving the outline hashes.

**Comment by frankrolf** [comment]
That sounds totally reasonable to me.
The logic of psautohint is always replacing the processed layer with the latest, so it doesn’t make much sense to keep an outdated layer around.

Another idea (not sure it’s genius or totally confusing):
If `psautohint` is run with the `--write-to-default-layer` option, the internal process could just make the processed layer be the foreground layer as a last step, and keep the former foreground layer around. That way, no overlaps can be lost accidentally.

**Comment by khaledhosny** [comment]
I have no strong opinion either way, whatever you feel best is fine for me.

**Comment by miguelsousa** [comment]
> the internal process could just make the processed layer be the foreground layer as a last step, and keep the former foreground layer around

That would require quite a bit of hacking, and I'm not convinced that it'd be a good step forward.

> That way, no overlaps can be lost accidentally.

psautohint does not remove overlaps; the only "destructive" action it does when writing to the default layer is decomposing composite glyphs. But I understand your idea.

I've thought about the destructive aspect of the `--write-to-default-layer` option (available in psautohint, autohint and checkoutlinesufo) many times and for me it all comes down to the user understanding when it should/shouldn't be used. It's off by default, so people can't really damage their fonts by accident.

**Comment by frankrolf** [comment]
Of course, all true. That said, yours still is a good idea.
