### ISSUE TITLE
Drop support for Python 2.7

### ISSUE THREAD

**Issue by josh-hadley** [adobe-type-tools/psautohint#175]
Synchronizing with recent updates to [AFDKO](https://github.com/adobe-type-tools/afdko/issues/741) and anticipating [Python 2.7's EOL as of January 1, 2020](https://pythonclock.org/), psautohint will only support Python 3.6+ moving forward. Code specific to supporting older Python will be removed.

- [x] update CI
- [x] remove `__future__` imports
- [x] remove use of `fontTools.misc.py23`
- [x] replace use of `.format()` with f-strings
- [x] update documentation
- [x] update `_psautohint.c` (remove `#if` conditional blocks for `PY_MAJOR_VERSION`)

**Comment by miguelsousa** [comment]
@josh-hadley you should issue on last stable release that supports 2.7. The latest release is a beta.

**Comment by josh-hadley** [comment]
@miguelsousa, @khaledhosny: currently we have `tox` pinned to v3.9.0, with a note in dev-requirements.txt that suggests this is being done for Python 2.7 compatibility. [Current `tox`](https://pypi.org/project/tox/#history) is 3.13.12. I tried updating to that version locally and tests succeeded, however I did get some UserWarnings coming from pyparsing (which reads requirements). I can investigate the warnings further but in general do either of you have objections to updating tox to the latest (pin to 3.13.12 and/or remove `pyup: ignore`)?

**Comment by khaledhosny** [comment]
No objection, it was indeed because tox or one of its dependencies dropped Python 2.7 support.

**Comment by josh-hadley** [comment]
I'm deferring the removal of `fontTools.misc.py23` indefinitely. Much of the use of it in `psautohint` seems to be beyond just smoothing gaps between Python 2 vs 3. For example, several methods use `tobytes` and `tounicode` to essentially "ensure" the desired type (those functions do a test on the input and if it is already the desired type, simply return the input, only converting to the desired type if it is not that type already). Some simple tinkering around with this indicates that the test code is not consistent with inputs for these methods (sometimes it's bytes, sometimes strings/Unicode), and patching things up to be consistent is a bit more than I want to get into right now.

Other changes in this task (particularly, removal of `__future__` imports and use of f-strings) will enforce the use Python 3.6+, so I'm not too concerned about leaving the `fontTools.misc.py23` stuff there (for now, anyway).

**Comment by anthrotype** [comment]
but from next fonttools v4.0, that module will be gone, so I'd recommed you fix those if you can.

**Comment by anthrotype** [comment]
well, not gone immediately; we'll keep the python3-only symbols from that module and issue a DeprecationWarning at first, then after a couple releases we can delete it for good.

**Comment by anthrotype** [comment]
but now is a good time to review all the call sites that accept either bytes or unicode strings and finally get rid of them. There is no such thing in python 3, for good reasons :)

**Comment by josh-hadley** [comment]
OK. I guess this task will just take a while longer than I'd estimated :-(

**Comment by khaledhosny** [comment]
> I'm deferring the removal of `fontTools.misc.py23` indefinitely. Much of the use of it in `psautohint` seems to be beyond just smoothing gaps between Python 2 vs 3. For example, several methods use `tobytes` and `tounicode` to essentially "ensure" the desired type (those functions do a test on the input and if it is already the desired type, simply return the input, only converting to the desired type if it is not that type already). Some simple tinkering around with this indicates that the test code is not consistent with inputs for these methods (sometimes it's bytes, sometimes strings/Unicode), and patching things up to be consistent is a bit more than I want to get into right now.

I don’t recall things being that messy. Basically the C module only takes bytes (for simplicity, it could have accepted strings/unicode objects and converted them to UTF-8, but the cpython API for that is awkward to work with). Since Python 2 don’t have such distinction and the Python code was written originally for Python 2, I enforced the bytes restriction only right before calling the C module.

I suggest making the code work with strings everywhere (since that makes the Python code simpler) and converting to bytes before calling the C module.

**Comment by josh-hadley** [comment]
@khaledhosny after some wrangling, I got things sorted out, using the approach you recommended.
