### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by jbicha** [adobe-type-tools/psautohint#18]
GNOME's Cantarell Fonts just released version 0.100 and it uses fontmake and psautohint to build the font from source. Could you please tag a release of psautohint to make it easier for distros to package this?

**Comment by khaledhosny** [comment]
I’m not sure this is ready to packaged or whether we want people to use this repository or wait until it is merged back into AFDKO. @miguelsousa what do you think?

**Comment by fabiangreffrath** [comment]
> I’m not sure this is ready to packaged or whether we want people to use this repository

Sorry, but I think it is already a little late for this consideration. As @jbicha mentioned, releases of major fonts have already been made that depend on this software. ;)

**Comment by madig** [comment]
(We also use the package internally at Dalton Maag :wink:)

**Comment by miguelsousa** [comment]
@khaledhosny I think we should move the repository to the adobe-type-tools organization now and tag it there.

**Comment by khaledhosny** [comment]
I just tagged a v1.1.0 release.
