### ISSUE TITLE
Provide more verbosity on "Failure in processing outline data" error

### ISSUE THREAD

**Issue by kontur** [adobe-type-tools/psautohint#201]
Is there any way that this [ACHintError](https://github.com/adobe-type-tools/psautohint/blob/71bae7b8e3b212ce1e422c6c0bf6bdd3d50f285c/python/psautohint/autohint.py#L582) could be more verbose as to what is causing hinting to fail?

Working on a family of four widths and only for one style of one width one particular glyph is failing, and furthermore than is a component glyph of which both components alone or with other glyphs do not fail. The error message does not really provide any insight to the root cause of the problem, so atm one is left guessing, more or less.

**Comment by skef** [comment]
This should no longer be an issue in otfautohint, which has been merged and will soon be released as part of afdko.
