### ISSUE TITLE
Fix sparse master compatible hinting

### ISSUE THREAD

**Issue by josh-hadley** [adobe-type-tools/psautohint#202]
In autohint.py, [`hint_compatible_glyphs`](https://github.com/adobe-type-tools/psautohint/blob/c048b63637b32d022443fd8b4f109da6fc2967dd/python/psautohint/autohint.py#L617) currently uses a hack to deal with sparse masters. The root cause is that the C implementation (`_psautohint.autohintmm`) does not support sparse masters. The current workaround works perfectly fine, but it would be nice and probably marginally more efficient if we didn't need to use it.

So ideally, we'd like to remove the hack code and be able to pass sparse master data directly to `_psautohint.autohintmm` and avoid pre-processing tricks in the Python code.

Rough to-do list:
 - [ ] update C code to properly handle sparse masters
 - [ ] remove Python hack
 - [ ] apply any additional updates to Python code to ensure things work smoothly

**Comment by khaledhosny** [comment]
I *think* the way to fix this is to checks if the glyph is present in all masters and use the commented out code, otherwise use the existing code. This would enable the optimization whenever it is possible without breaking sparse masters.

**Comment by skef** [comment]
This is no longer an issue in the `pyport` branch.

**Comment by skef** [comment]
Fixed in otfautohint.
