### ISSUE TITLE
Add Python 3.8 to tox config

### ISSUE THREAD

**Issue by josh-hadley** [adobe-type-tools/psautohint#208]
Currently we are only running py36 and py37...add py38

**Comment by madig** [comment]
Please also add 3.8 wheels. May need multibuild updates?

**Comment by josh-hadley** [comment]
> Please also add 3.8 wheels. May need multibuild updates?

Right, probably a good idea to doo all of the Python 3.8 stuff at the same time.

**Comment by josh-hadley** [comment]
I have added a [GitHub Action/workflow](https://github.com/adobe-type-tools/psautohint/actions) to run the test suite under a variety of Python versions and operating systems including Python 3.8. So I'm going to close this issue (but I will open another one to capture the task of building 3.8 wheels, which will eventually happen, most likely as a GitHub Action as well).

**Comment by madig** [comment]
Cool, I have been meaning to look into GH Actions to replace all the other CIs for font stuff but haven't had the time yet. I wonder how well wheel building works there...

**Comment by josh-hadley** [comment]
I intend to find out soon :-) There are instructions on [how to generically build and publish a Python package](https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries) as well as a predefined [GH Action for building **manylinux** wheels](https://github.com/RalfG/python-wheels-manylinux-build) that I will be trying out here some time soon. And, as you might guess, if/when I get things working well here, I'll try to apply that to AFDKO as well (though that can be a lot more tricky to build/package correctly).

**Comment by miguelsousa** [comment]
Done as part of #242
