### ISSUE TITLE
“Conflicts with current hints” with flipped components

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/psautohint#218]
(perhaps related to #149)

In the attached UFO file, only two glyphs exist:
`braceleft`, and a composite glyph `braceright`, obtained by via point-reflection of a single component (`scale (-1, -1)`).

when hinting this file, `psautohint` will always output the following error:

```
ERROR: braceright:   Conflicts with current hints: 0 720 0 700 b.
ERROR: braceright:   Conflicts with current hints: 0 633 0 720 b.
```

Why? What does it mean?
Does this mean that `psautohint` cannot deal with flipped components?

[Braces-MediumItalic.ufo.zip](https://github.com/adobe-type-tools/psautohint/files/3936268/Braces-MediumItalic.ufo.zip)

**Comment by skef** [comment]
The `pyport` branch doesn't seem to do anything unexpected with these files.

**Comment by skef** [comment]
Fixed in otfautohint.
