### ISSUE TITLE
Not all invalid hints are are removed from VF font

### ISSUE THREAD

**Issue by readroberts** [adobe-type-tools/psautohint#219]
When looking at issue #189 in Cantarell-VF.otf, I noticed that 'tx' reported that some hints for the ExtraLight master had top and bottom edge reversed, such as "107 102 vstem" in glyph uni0213, and some glyphs had overlapping hints. This shows that there are bugs in the logic for filtering out invalid hints for the region fonts after deriving hints from the default font.

**Comment by skef** [comment]
Stems with reversed locations in a master should be removed from the final set in the `pyport` branch, with a warning printed when one is encountered.

**Comment by skef** [comment]
fixed in otfautohint.
