### ISSUE TITLE
Performance on variable fonts?

### ISSUE THREAD

**Issue by madig** [adobe-type-tools/psautohint#221]
Hinting Cantarell-VF takes a long time on my Ryzen 1700. I used https://github.com/benfred/py-spy to profile the run and had it generate a speedscope file: [profile.zip](https://github.com/adobe-type-tools/psautohint/files/4055894/profile.zip). The file can be loaded on https://www.speedscope.app/.

Something like 90% of the time is spent in `SimpleT2Decompiler.execute`, which itself spends most of that time in `T2CharString.getToken`. If performance gets on the todo list, this is probably a good place to start looking.

**Comment by josh-hadley** [comment]
Just noting that these routines are actually in the fonttools codebase: https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/misc/psCharStrings.py

**Comment by madig** [comment]
Wherein I look at a debugger and scratch my head: so I put a `logging.warning` before and after https://github.com/fonttools/fonttools/blob/4.18.2/Lib/fontTools/subset/cff.py#L492 because the profiler says 90% of time is spent in there and it dutifully prints me a list of processed glyph names. And then it keeps going for a long time after the end, without triggering any more logging messages. Ctrl+C-ing at some point does show exactly that line in the backtrace though and going up the stack frames reveals that the same glyph names that were processed the first time around show up again. Huh. Almost as if the same glyphs are desubroutinized over and over again, but somehow without triggering my loggers.
