### ISSUE TITLE
-x fails with maximum recursion error

### ISSUE THREAD

**Issue by kontur** [adobe-type-tools/psautohint#223]
Hey,

I'm trying to autohint a font, but hit a hinting error on a particular glyph. I am trying to exclude that particular glyph with `-x`, but always hit another error relating to the`-x` param. Using `-g` on the same glyph (to verify syntax / CID accessing) as expected I get the same initial hinting error.

```
$ psautohint -vv Font.otf
...hinting
DEBUG: u043B.smcp: 54.5  u043B.smcp                    439.5  494
ERROR: u043B.smcp:   Conflicts with current hints: 0 -6 0 76 b.
ERROR: u043B.smcp: Uninitialized extra hints list.
ERROR: u043B.smcp: Failure in processing outline data.

$ psautohint -vv -x u043B.smcp Font.otf
DEBUG: Reading 'CFF ' table from disk
DEBUG: Decompiling 'CFF ' table
ERROR: maximum recursion depth exceeded

$ psautohint -vv -g u043B.smcp Font.otf
...hinting
DEBUG: u043B.smcp: 54.5  u043B.smcp                    439.5  494
ERROR: u043B.smcp:   Conflicts with current hints: 0 -6 0 76 b.
ERROR: u043B.smcp: Uninitialized extra hints list.
ERROR: u043B.smcp: Failure in processing outline data.

What's causing the -x to fail?

**Comment by kontur** [comment]
What's more, `--exclude-glyphs-file` seems to first interpret the file contents as string arrays instead of glyph names, but then fails with the same error:

```
$ cat excl.txt
u043B.smcp
$ psautohint -vv --exclude-glyphs-file excl.txt Font.otf
DEBUG: Reading 'CFF ' table from disk
DEBUG: Decompiling 'CFF ' table
WARNING: glyph ID <u> from glyph selection list option is not in font. <Font.otf>.
WARNING: glyph ID <0> from glyph selection list option is not in font. <Font.otf>.
WARNING: glyph ID <4> from glyph selection list option is not in font. <Font.otf>.
WARNING: glyph ID <3> from glyph selection list option is not in font. <Font.otf>.
WARNING: glyph ID <B> from glyph selection list option is not in font. <Font.otf>.
WARNING: glyph ID <.> from glyph selection list option is not in font. <Font.otf>.
WARNING: glyph ID <s> from glyph selection list option is not in font. <Font.otf>.
WARNING: glyph ID <m> from glyph selection list option is not in font. <Font.otf>.
WARNING: glyph ID <c> from glyph selection list option is not in font. <Font.otf>.
WARNING: glyph ID <p> from glyph selection list option is not in font. <Font.otf>.
WARNING: glyph ID <
> from glyph selection list option is not in font. <Font.otf>.
ERROR: maximum recursion depth exceeded
```

All this on psautohint `2.0.0`

**Comment by kontur** [comment]
Ah, and I noticed the `--traceback` param, which yields probably useful info :)

```
$ psautohint -vv -x u043B.smcp --traceback Font.otf
DEBUG: Reading 'CFF ' table from disk
DEBUG: Decompiling 'CFF ' table
Traceback (most recent call last):
  File "/Users/johannes/Library/Python/3.7/bin/psautohint", line 8, in <module>
    sys.exit(main())
  File "/Users/johannes/Library/Python/3.7/lib/python/site-packages/psautohint/__main__.py", line 914, in main
    hintFiles(options)
  File "/Users/johannes/Library/Python/3.7/lib/python/site-packages/psautohint/autohint.py", line 918, in hintFiles
    hint_regular_fonts(options, fonts, paths, outpaths)
  File "/Users/johannes/Library/Python/3.7/lib/python/site-packages/psautohint/autohint.py", line 848, in hint_regular_fonts
    False)
  File "/Users/johannes/Library/Python/3.7/lib/python/site-packages/psautohint/autohint.py", line 500, in get_fontinfo_list
    return get_fontinfo_list_withFontInfo(options, font, path, glyph_list)
  File "/Users/johannes/Library/Python/3.7/lib/python/site-packages/psautohint/autohint.py", line 572, in get_fontinfo_list_withFontInfo
    for name in glyph_list:
  File "/Users/johannes/Library/Python/3.7/lib/python/site-packages/psautohint/autohint.py", line 365, in <lambda>
    newList = filter(lambda name: name not in glyphList, fontGlyphList)
  File "/Users/johannes/Library/Python/3.7/lib/python/site-packages/psautohint/autohint.py", line 365, in <lambda>
    newList = filter(lambda name: name not in glyphList, fontGlyphList)
  File "/Users/johannes/Library/Python/3.7/lib/python/site-packages/psautohint/autohint.py", line 365, in <lambda>
    newList = filter(lambda name: name not in glyphList, fontGlyphList)
  [Previous line repeated 991 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by kontur** [comment]
That seems to at least fix the recursion warning, but I am unsure how the --exclude-glyphs-file is _supposed_ to be parsed, so I left that untouched.

**Comment by frankrolf** [comment]
It took me a while to find the syntax of the glyphs file, it may be worthwhile to repeat ❝`The file must contain a comma-separated sequence of glyph identifiers.`❞ in the help string for `--exclude-glyphs-file`.

Anyway, testing with this file:
```
A,B,C

```

`psautohint --exclude-glyphs-file exclude.txt test.ufo`
```
WARNING: glyph ID <,> from glyph selection list option is not in font. <test.ufo>.
WARNING: glyph ID <
> from glyph selection list option is not in font. <test.ufo>.
ERROR: object of type 'filter' has no len()
```

---

Another file:
```
1,2,3

```
`psautohint --exclude-glyphs-file exclude.txt test.ufo`
```
WARNING: glyph ID <1> from glyph selection list option is not in font. <test.ufo>.
WARNING: glyph ID <,> from glyph selection list option is not in font. <test.ufo>.
WARNING: glyph ID <2> from glyph selection list option is not in font. <test.ufo>.
WARNING: glyph ID <3> from glyph selection list option is not in font. <test.ufo>.
WARNING: glyph ID <
> from glyph selection list option is not in font. <test.ufo>.
ERROR: object of type 'filter' has no len()
```

---

The same error message appears with
`psautohint -x A,B,C test.ufo`
```ERROR: object of type 'filter' has no len()```

---

I see two different issues:
- the parsing of the external file is failing (see comma and return being read in as glyph IDs)
- a probable Python2- vs 3 difference in the object expected for filtered glyphs. See here:

`psautohint --traceback -x A,B,C test.ufo`

```
Traceback (most recent call last):
  File "/Users/fgriessh/.pyenv/versions/3.7.4/bin/psautohint", line 8, in <module>
    sys.exit(main())
  File "/Users/fgriessh/.pyenv/versions/3.7.4/lib/python3.7/site-packages/psautohint/__main__.py", line 914, in main
    hintFiles(options)
  File "/Users/fgriessh/.pyenv/versions/3.7.4/lib/python3.7/site-packages/psautohint/autohint.py", line 918, in hintFiles
    hint_regular_fonts(options, fonts, paths, outpaths)
  File "/Users/fgriessh/.pyenv/versions/3.7.4/lib/python3.7/site-packages/psautohint/autohint.py", line 857, in hint_regular_fonts
    hinted = hint_font(options, font, glyph_names, fontinfo_list)
  File "/Users/fgriessh/.pyenv/versions/3.7.4/lib/python3.7/site-packages/psautohint/autohint.py", line 688, in hint_font
    glyphs = get_bez_glyphs(options, font, glyph_list)
  File "/Users/fgriessh/.pyenv/versions/3.7.4/lib/python3.7/site-packages/psautohint/autohint.py", line 473, in get_bez_glyphs
    total = len(glyph_list)
TypeError: object of type 'filter' has no len()
```

**Comment by frankrolf** [comment]
The 2nd issue disappears if I change [this line](https://github.com/adobe-type-tools/psautohint/blob/master/python/psautohint/autohint.py#L473)
from
`    total = len(glyph_list)`
 to 
`    total = len(list(glyph_list))`

But I don’t think that’ll fix the root issue of a filter object being passed around.

**Comment by kontur** [comment]
Thanks for your input @frankrolf !

It would seem odd that the syntax for the exclude file content this should contradict the [glyphsList](https://github.com/adobe-type-tools/psautohint/blob/master/python/psautohint/autohint.py#L5), no?

> # Parse args. If glyphlist is from file, read in entire file as single string,
> # and remove all white space, then parse out glyph-names and GID's.

Either way, it should read a single glyph name as a single item of a list, not as item per char in the string.

---

I found one other odd thing when playing with the [filterGlyphList](https://github.com/adobe-type-tools/psautohint/blob/master/python/psautohint/autohint.py#L351) code some more. When running from CLI, the `options.glyphList` is somehow not False (I haven't looked for the code that presumably populates it), but when instantiating a default ACOptions object and setting only `excludeGlyphList`, the `not option.glyphList` will be triggered by the default which is an [empty list here](https://github.com/adobe-type-tools/psautohint/blob/master/python/psautohint/autohint.py#L53):

```
if not options.glyphList:
        glyphList = fontGlyphList
...
```

And thus it never enters the `else` loop to actually exclude those glyphs.

**Comment by kontur** [comment]
That is to say, it seems `filterGlyphList` accepts either a list as subset, or a list to subtract from the font, but not both, which it probably should.

To my mind it should take the font's glyphs, intersect with glyphsList if set, and subtract excludeGlyphsList from it, if set.

**Comment by josh-hadley** [comment]
fixed in https://github.com/adobe-type-tools/psautohint/pull/224
