### ISSUE TITLE
Add option to dehint a font

### ISSUE THREAD

**Issue by kontur** [adobe-type-tools/psautohint#241]
It would be useful to have a quick and reliable way to remove CFF hints from a font. Akin to `ttfautohint`'s `-d` option.

**Comment by frankrolf** [comment]
I think `tx` might be able to do that – have you tried playing around with it?

**Comment by kontur** [comment]
Hey, do you mean `ttx`/fonttools? That would have been my go to for hacking this, but I was wondering if psautohint could, even if just eventually, support this out of the box.

**Comment by frankrolf** [comment]
No, I mean `tx`, part of the FDK: https://github.com/adobe-type-tools/afdko/blob/develop/docs/AFDKO-Overview.md#tx

**Comment by kontur** [comment]
At least the documentation does not seem to imply that this would remove hints and leave the font otherwise unchanged. Do you know a particular parameter/option to use with the `tx` command? Just running it on a CFF OTF (like `tx in.otf out.otf`) seems to do _something_, but not generate a font without hints (:

**Comment by cjchapman** [comment]
```
$ tx -u | grep -i hint
-n              remove hints
``

**Comment by josh-hadley** [comment]
@kontur I just added a How-to for this in the AFDKO Wiki: https://github.com/adobe-type-tools/afdko/wiki/How-To#how-to-remove-hints-from-a-cff-based-otf

**Comment by josh-hadley** [comment]
@kontour I'm going to close this issue now; if you are still having problems please re-open and we'll try to help get you sorted out.

**Comment by kontur** [comment]
Thanks all for the comments and instructions.

I tried `tx help` and `tx --help`, but `tx -h` seems to be what I was guessing for ;)

For the benefit of others finding this thread, I tried different methods for a 207K otf file:

- the wiki how to gives me a 172K file, thanks @josh-hadley
- using fontTools' `pyftsubset --no-hinting` gives me a 183K file (some of the default values might affect size here one way or another)
- `tx -n old.otf new.otf` (or `tx -n -cff old.otf new.otf`) writes a 109K file, but it's not a readable otf

**Comment by josh-hadley** [comment]
> * `tx -n old.otf new.otf` (or `tx -n -cff old.otf new.otf`) writes a 109K file, but it's not a readable otf

Right, the `-cff` option ("mode") of `tx` writes the modified CFF **table** (_not_ the whole OTF font) into a file. Using the `.otf` filename extension does not change that behavior. That is why the How To describes a two-step process to go OTF-to-OTF: first with `tx` to remove the hints and generate a CFF-table-in-file, then `sfntedit` to replace the CFF table with the generated CFF-table-in-file. Also, be sure to use the `+b` option for `tx` to preserve the glyph order, you can get some unexpected results if you don't.
