### ISSUE TITLE
Access psautohint version used to hint a font

### ISSUE THREAD

**Issue by kontur** [adobe-type-tools/psautohint#243]
Is there a way to access what version of psautohint was used to hint a font? If not, this would be a really useful addition for font versioning and consistency checks e.g. in [a fontbakery check](https://github.com/googlefonts/fontbakery/issues/2802).

**Comment by anthrotype** [comment]
import psautohint
print(psautohint.__version__)

**Comment by kontur** [comment]
Ah, sorry, my wording was a bit loose there. What I meant is a version string left somewhere _in the hinted font_, akin to what ttfautohint or makeotf leave in the version name table entry.

**Comment by josh-hadley** [comment]
`psautohint` does not alter name table entries and there are no other tool-specific "marks" left in the font that would enable identifying the specific version used (or even that `psautohint` specifically was used).

We discussed possibly implementing this idea, but quickly came to the conclusion that it would cause more problems than it solves. There are just too many ways to end up with outdated, incomplete, or just flat-out incorrect information in a name string (out-of-band edits, multiple versions of the same tool modifying different glyphs, etc.).

**Comment by kontur** [comment]
Thanks once again for clarifying, @josh-hadley
