### ISSUE TITLE
codecov.io no longer shows coverage for C code

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/psautohint#248]
I think that is similar to https://github.com/adobe-type-tools/afdko/issues/1128, related to the switch to GitHub Actions perhaps?

**Comment by josh-hadley** [comment]
GitHub Actions were _added_; we haven't removed any other CI (yet). Possible token expiration or some such. I'll investigate. Thanks for catching this.

**Comment by josh-hadley** [comment]
Reviewing the trees on codecov.io, It looks like #239 was the last one where C coverage was reported: [codecov 239](https://codecov.io/gh/adobe-type-tools/psautohint/pull/239/tree). It goes missing as of #240: [codecov 240](https://codecov.io/gh/adobe-type-tools/psautohint/pull/240/tree).

Both of these occurred well after GitHub Actions were introduced, so I'm pretty confident that Actions are not to blame.

I'll check AFDKO to see if C coverage reporting failed around the same time. If so, maybe some setting needs to be updated in [.codecov.yml](https://github.com/adobe-type-tools/psautohint/blob/master/.codecov.yml) or maybe one of the CI-only dependencies needs updating.

**Comment by khaledhosny** [comment]
Checking the last built, it seems that the job that runs `tox -e coverage-codecov-c` is [erroring at the end](https://travis-ci.org/github/adobe-type-tools/psautohint/jobs/677336126#L1001):
```
coverage-codecov-c runtests: commands[2] | codecov --env coverage-codecov-c

find: unknown predicate `-not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**''

      _____          _

     / ____|        | |

    | |     ___   __| | ___  ___ _____   __

    | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /

    | |___| (_) | (_| |  __/ (_| (_) \ V /

     \_____\___/ \____|\___|\___\___/ \_/

                                    v2.0.22

==> Detecting CI provider

    Travis Detected

==> Preparing upload

==> Processing gcov (disable by -X gcov)

    Executing gcov (['find', '/home/travis/build/adobe-type-tools/psautohint', "-not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**'", '-type', 'f', '-name', '*.gcno', '', '-exec', 'gcov', '-pb', '', '{}', '+'])

    Error running `['find', '/home/travis/build/adobe-type-tools/psautohint', "-not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**'", '-type', 'f', '-name', '*.gcno', '', '-exec', 'gcov', '-pb', '', '{}', '+']`: Command '['find', '/home/travis/build/adobe-type-tools/psautohint', "-not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**'", '-type', 'f', '-name', '*.gcno', '', '-exec', 'gcov', '-pb', '', '{}', '+']' returned non-zero exit status 1.

==> Collecting reports

Error: No coverage report found
```

**Comment by khaledhosny** [comment]
May be gcov is no longer installed?

**Comment by josh-hadley** [comment]
@khaledhosny I decided to side-step debugging of the current problem with Travis, and I implemented coverage generation & uploading to codecov.io via GitHub Actions. Here's the result: https://codecov.io/gh/adobe-type-tools/psautohint/tree/20b3420faf69657f956771a8b4a3e714dac4ecd1

And if you look at the 'Build' for that you can see that it comes entirely from GitHub Actions (not Travis or Appveyor, as can be seen in other builds on codecov.io).

I haven't carefully checked the coverage results compared to before we lost C coverage, but at first glance it looked reasonable to me. If you could have a look and confirm when you get a chance that would be great. And then I'll probably turn off the codecov.io in other CIs (they won't be disconnected completely, yet, because there are still actions in there that we aren't doing via GHA yet).

**Comment by khaledhosny** [comment]
Thanks, looks good to me. The coverage is lightly up from the last build with C coverage, and it looks like lines that previously showed partial coverage (yellow) are now showing full coverage (green), not sure if we really had more tests in the meantime or just different compiler output, but it does not look like something to worry about.

**Comment by josh-hadley** [comment]
Looks like there's no partial coverage reported for any of the C code (there is for Python). Possibly a switch or flag for either `gcov` or `codecov.io`. I'll dig around a bit and see if I can find anything.

**Comment by josh-hadley** [comment]
Possible cause of dropped partial coverage: https://docs.codecov.io/docs/codecov-yaml#can-i-name-the-file-codecovyml (ours currently is named `.codecov.yml` and the GHA uses the bash script for uploading. I'll try using the `-y <conf file>` option there as recommended.

**Comment by josh-hadley** [comment]
As with adobe-type-tools/afdko#1128, I think this is sufficiently addressed and I am closing it. Please re-open or create a new issue if this comes up again.
