### ISSUE TITLE
Deprecation/compatibility option not shown for some options

### ISSUE THREAD

**Issue by josh-hadley** [adobe-type-tools/psautohint#260]
In [an AFDKO review relating to psautohint](https://github.com/adobe-type-tools/afdko/pull/1175#discussion_r445779690) it was noted that a deprecation message does not appear when the legacy `-hfd` flag is used. The deprecation warning does appear for other legacy options, e.g. `-pfdl`.

Cause appears to be in https://github.com/adobe-type-tools/psautohint/blob/d1ca70affebe4f070037365d44780ab8a78778b0/python/psautohint/__main__.py#L829-L835
The `action` does not use `_DeprecatedAction` like other deprecated/legacy compatibility options do.

**Comment by miguelsousa** [comment]
Instead of trying to fix it it may be time to remove the support for the legacy options, since it was meant to be temporary anyway.

**Comment by josh-hadley** [comment]
Yeah, maybe so. Either way seems pretty low priority.
