### ISSUE TITLE
Crash with complex glyphs

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/psautohint#266]
I have a font where certain glyphs crash psautohint. Here is a subset font with the offending glyphs:  [STIXTwoMath-Regular.subset.zip](https://github.com/adobe-type-tools/psautohint/files/5242380/STIXTwoMath-Regular.subset.zip)

**Comment by khaledhosny** [comment]
cc @tiroj

**Comment by cjchapman** [comment]
@khaledhosny (cc: @tiroj & @josh-hadley) I believe this is already fixed by https://github.com/adobe-type-tools/psautohint/pull/263.

Please try:
```bash
pip3 install --pre psautohint
```
to pick up the 2.1.1a0 release and confirm.

**Comment by josh-hadley** [comment]
I checked with the 2.1.1a0 pre-release and it does not crash on that font (it _does_ throw an error: `ERROR: uniE0F5.nu: Check for duplicate subpath at 351 589.`, but no segfault like the current version).

**Comment by khaledhosny** [comment]
Yes, it is fixed indeed (that explains why I couldn’t reproduce with the standalone `autohintexe`. Sorry for noise.

**Comment by josh-hadley** [comment]
Just noting that I released 2.1.1 so newer installs/upgrades will pick up the fix.

**Comment by khaledhosny** [comment]
I already updated to release version, thanks!
