### ISSUE TITLE
Please mark alpha releases as such on GitHub

### ISSUE THREAD

**Issue by alerque** [adobe-type-tools/psautohint#271]
GitHub's releases have a flag for "pre-release" as opposed to final stable releases. I can guess from the `a0` suffix that the recent tags are considered alphas, but there are many ways the GitHub API makes it easier to automate distro packaging management if the status of releases is saved correctly. It would be nice if the alphas were tagged as pre-releases rather than being the latest stable.

**Comment by josh-hadley** [comment]
Sorry about that — we're doing some testing for an unexpectedly accelerated switch away from third-party CIs (Travis, specifically) to GitHub Actions and missed that detail. I've manually flagged those 2 test releases as pre-release, but will update the workflow so it's automatic for future [pre-] releases. Next one will be soon (although, like these recent tests, won't really have any changes from v2.1.1).

**Comment by alerque** [comment]
Given the beta release just posted showed up tagged as a pre-release, this seems to be resolved. Thanks!

**Comment by josh-hadley** [comment]
Yes! I have one minor tweak to make on the release process, but in general this should be sorted now. Thanks for your patience!
