### ISSUE TITLE
Use argparse

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/psautohint#28]
Switching to `argparse` will break backwards compatibility with many existing options, so we have the chance to rethink them all. This work should be completed before #19.

**Comment by khaledhosny** [comment]
Right. I considered this before but was worried about backward compatibility. Though the current command line parsing is a bit convoluted, I didn’t feel like breaking existing scripts (or making it hard for people to switch to this from the old `autohint`) is worth the trouble.

**Comment by miguelsousa** [comment]
The multi-letter options with a single hyphen prefix are non-standard, and the current parsing code is messy. I think we can easily justify the breakage.

**Comment by madig** [comment]
And people can easily use the AFDKO autohint I guess?

**Comment by miguelsousa** [comment]
> And people can easily use the AFDKO autohint I guess?

Yes. There's some discussion on 26b0e75476d6d1726ae206297a18a539b4d966d1 if you're interested.
