### ISSUE TITLE
test_hashmap_old_version is unreliable

### ISSUE THREAD

**Issue by sternenseemann** [adobe-type-tools/psautohint#284]
Seems like there's a race condition involved or something maybe. Have seen the test both fail and succeed in unchanged environments in our [`nixpkgs` package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/psautohint/default.nix)

* aarch64
  * [build log of failure](https://hydra.nixos.org/build/131988272/nixlog/1)
  * [build log of success](https://hydra.nixos.org/build/131082223/log)
* x86_64
  * [build log of failure](https://hydra.nixos.org/build/132339547/nixlog/1)
  * [build log of success](https://hydra.nixos.org/build/132373194/log)

These failures have been popping up only recently, so they might be related to a dependency being updated. However I've also seen the tests succeed with the current state of things.

**Comment by josh-hadley** [comment]
I suspect this is related to an issue we've been experiencing with `pytest` and our tests' use of `caplog`. See https://github.com/adobe-type-tools/psautohint/pull/264

Our test suite(s) specify:
```
  pytest  >= 5.3.0, < 6.0.0
  pytest-xdist < 2.0.0
```
as the issue in pytest was introduced in 6.0.0 and apparently hasn't been resolved. 

Looking at the logs you posted, the failure cases are using pytest >= 6.0.0, while the success cases use pytest < 6.0.0.

I'm not sure if this will ever get addressed in `pytest`, so we might eventually be forced to change our tests' usage of `caplog` but I think for now we can continue with the older pinned version.

**Comment by sternenseemann** [comment]
Thanks! Wouldn't have spotted that pytest was the issue.

**Comment by josh-hadley** [comment]
> Thanks! Wouldn't have spotted that pytest was the issue.

Understandable, because we don't list `pytest` in `requirements.txt` or `dev-requirements.txt` -- it's only in the test workflows and `tox.ini` and probably your test scheme does not read those.

**Comment by miguelsousa** [comment]
[This commit](https://github.com/adobe-type-tools/psautohint/pull/347/commits/54d01d3111da832908a1b756ca9f298f9f45b240) may have finally fixed this reoccurring problem.
