### ISSUE TITLE
psautohint is unusable as a module...

### ISSUE THREAD

**Issue by typemytype** [adobe-type-tools/psautohint#298]
1)

```python
from psautohint.__main__ import get_options, hintFiles

path = 'a/path/to/a/not/existing/font.otf'

args = [
    "--no-zones-stems",
    "--all",
    path 
]

options, pargs = get_options(args)
hintFiles(options)
```

there are several `exits` in the c code, which just force stops any process where, this is not nice, only the main terminal callback should exit

----
2)

the c code fprintf is not 'catchable' in the stdout or stderr, if you change the path to an actual font file, the callback `hintfiles(options)` does not report (print out) anything (ERRORS, WARNING...) which is not good

**Comment by khaledhosny** [comment]
The only `fprintf()` and `exit()` calls in the repository are in the `autohintexe` executable, which is not used from Python code (not for a while now).

**Comment by khaledhosny** [comment]
But anyway, the Python code have not been designed as a usable module and does not currently guarantee any API stability, the only officially supported API is the command line.

**Comment by iterumllc** [comment]
This should no longer be an issue with the `pyport` branch.

**Comment by skef** [comment]
otfautohint should be usable as a module, as it is entirely python now.
