### ISSUE TITLE
flattenBlends should test on empty incoming list

### ISSUE THREAD

**Issue by typemytype** [adobe-type-tools/psautohint#302]
blue values or V/H stem list could be empty

https://github.com/adobe-type-tools/psautohint/blob/master/python/psautohint/otfFont.py#L1015

```traceback
...
python3.7/psautohint/otfFont.py", line 1015, in flattenBlends
IndexError: list index out of range
```

**Comment by typemytype** [comment]
this happens when fe blues are set but no otherBlues

**Comment by iterumllc** [comment]
This should be fixed in the 'pyport' branch.

**Comment by frankrolf** [comment]
It’s hard to find that branch without a link @skef ;-)

**Comment by skef** [comment]
Refactored in otfautohint in afkdo
