### ISSUE TITLE
[tx] Using tx with CFF2 fonts causes outlines to disappear

### ISSUE THREAD

**Issue by punchcutter** [adobe-type-tools/psautohint#311]
Found through `psautohint` [here](https://github.com/adobe-fonts/source-han-sans/issues/296) When the outlines in both masters are identical they are removed completely from the resulting font. 

Attached is a simple test font with 2 glyphs: .notdef and A
The .notdef outlines are identical in both masters so it disappears when running `psautohint TestCFF2tx.otf`

[TestCFF2tx.otf.zip](https://github.com/adobe-type-tools/afdko/files/6311206/TestCFF2tx.otf.zip)

**Comment by iterumllc** [comment]
This should be fixed in the `pyport` branch.

**Comment by skef** [comment]
Fixed in otfautohint.
