### ISSUE TITLE
UFO notation of ghost stem hints

### ISSUE THREAD

**Issue by jenskutilek** [adobe-type-tools/psautohint#397]
Just to make sure this is correct … in an UFO I see this:

```xml
          <dict>
            <key>pointTag</key>
            <string>hintSet0003</string>
            <key>stems</key>
            <array>
              <string>hstem 21 -21</string>
              <string>hstem 501 -20</string>
              <string>vstem 67 130</string>
              <string>vstem 509 120</string>
            </array>
          </dict>
```

Is the notation given for the bottom ghost hint correct? The "hinted edge" for that ghost hint is at y=0. I kind of expected it to be written as `hstem 0 -21`.

**Comment by frankrolf** [comment]
I cannot say anything about the correctness of this without further investigation, but I think it would be helpful if you shared the whole glif file (if possible). Thanks :-)

**Comment by frankrolf** [comment]
A bit oldschool, but `hintplot font.ufo` does the job :-)
<img width="879" alt="Screenshot 2022-12-08 at 14 19 13" src="https://user-images.githubusercontent.com/2049645/206456751-539888d2-53a5-4167-bda0-8da208017bd9.png">

**Comment by frankrolf** [comment]
I have re-hinted the glyph in question (`psautohint --no-zones-stems shell.ufo`), and the ghost hint now looks like this:

<img width="1648" alt="Screenshot 2022-12-08 at 14 33 23" src="https://user-images.githubusercontent.com/2049645/206459506-0ddbb94e-05c0-460a-ba7f-c33b202a3ff4.png">

Interesting, perhaps more in line with what you were expecting.
To reproduce even better, I wonder how the original files were hinted, and which alignment zones were used?

@iterumllc, do yo know what could be going on?

**Comment by skef** [comment]
Unfortunately the replacement of a ghost stem with, I guess, a fully alive stem isn't evidence of much. On your re-hinting its decided to make one hstem from the baseline to the inside of the bottom of the bowl and the other hstem from the top of the inside of the bowl to the top of the (typographical) stem. Those are just (presumably) valid alternatives to the ghost encoding.

If I manipulate the glyph to move those stems to hintSet0000, delete the other data (and point names), put the glif into a ufo, convert to Type1, and `tx -dump -6` that file, I see :

```
glyph[1] {a,-,
  833 width
  0 bottomedge
  501 topedge
  67 197 vstem
  509 629 vstem
  67 248 move
  67 90 164 -24 329 -24 curve
  ...
```
And 0 and 501 are the right y-locations for that typographical stem on the right. 

This also matches my understanding of bottom ghost stem encodings. This is the usual example in the documentation: https://learn.microsoft.com/en-us/typography/opentype/otspec180/cff2charstr#Figure4 . Note that they start with an hstem from 100 to 121 in the image and that gets encoded as "121 -21 hstem". That's just how the powers that be back in the day decided to encode them.

**Comment by jenskutilek** [comment]
Ok, so everything seems ok. Thank you very much for your explanations!
