### ISSUE TITLE
Terminal process is hanging when run on M1 Mac

### ISSUE THREAD

**Issue by arrowtype** [adobe-type-tools/psautohint#400]
Hello, I really appreciate this project being a module, and it’s great to see that M1 support [has apparently been added with the latest release, v2.4.0](https://github.com/adobe-type-tools/psautohint/blob/master/NEWS.md#v240---February-2-2022).

Unfortunately, I am trying to run a font build on an M1 Mac for the first time, and finding that if I try to run psautohint, the process simply hangs. I don’t get an error message or anything. Beyond that, it seems to cause my terminal app to hang (whether in VS Code, iTerm2, or the basic Mac Terminal) ... even if I just run the simplest command, like `psautohint --help`.

<img width="570" alt="image" src="https://user-images.githubusercontent.com/45946693/231339914-b42758d6-a62c-4d2d-a656-f0c4cdcb50e0.png">

It will simply hang like that until I hit ctrl+C to quit the prompt.

Is there something I may have missed? Is there anything I can do to help investigate this further?

Thanks!

Setup:
- psautohint 2.4.0
- M1 Max
- macOS Ventura 13.0 (22A380)

**Comment by punchcutter** [comment]
Looks like you are running Python 3.11. Can you try with 3.10?

**Comment by arrowtype** [comment]
Amazing, that is super helpful – thank you so much!

**Comment by arrowtype** [comment]
I've closed the issue, as it is solved for me, and I assume the eventual update to Python 3.11 will be tracked elsewhere. Obviously, though, if maintainers want to reopen this, feel free to!
