### ISSUE TITLE
Change Travis CI to webhook

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/psautohint#48]
I don’t know what is going on, but Travis CI does not seem to run anymore, neither on branches (e.g. wip/test), nor in PRs (e.g. #47).

**Comment by miguelsousa** [comment]
I think I know what's going on. I deactivated the 'Service' thinking that we were already setup the way they want us to be going forward (because of https://developer.github.com/changes/2018-04-25-github-services-deprecation/), but we're not. It's active again. But leave this issue open to remind us to migrate to a webhook.

**Comment by khaledhosny** [comment]
Works again now indeed.

**Comment by miguelsousa** [comment]
sorry for the disruption

**Comment by miguelsousa** [comment]
the migration (from `travis-ci.org` to `travis-ci.com`) request has been submitted. Below is the notice displayed at https://www.travis-ci.com/adobe-type-tools/psautohint . So we just have to wait.
<img width="674" alt="travis-ci com" src="https://user-images.githubusercontent.com/2119742/42242625-65d842f8-7ec3-11e8-8ab0-80c97328d9c0.png">

**Comment by miguelsousa** [comment]
The notice is no longer the same, but the **Sign up for the beta** button is disabled.
<img width="762" alt="new_notice" src="https://user-images.githubusercontent.com/2119742/67324266-68c6b400-f4c8-11e9-8624-ca536a2f9ee3.png">

**Comment by josh-hadley** [comment]
@miguelsousa @khaledhosny please comment if this is still an issue, otherwise I'll go ahead and close.

**Comment by miguelsousa** [comment]
@josh-hadley GitHub Actions is the way forward. Closing.
