### ISSUE TITLE
Generated CFF table has undecodable subroutines

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/psautohint#67]
Checking the TTX dump of CFF tables generated by psautohint, the `Priviate.Subr` is full of undecoded CharStrings. I think this is because when we convert from CharStrings to bez format we “flatten” the subroutines, and when we convert back the old subroutines become unused and subsequently undecodable.

Not sure if we should do anything here as it probably only increases the file size. I considered just emptying `Priviate.Subr`, but this would break fonts where only a subset of the glyph are hinted (using the `-g` option). I don’t know if there is a way to detect unused subroutines and prune them.

**Comment by khaledhosny** [comment]
`GlobalSubrs` seems to be similarly affected.

**Comment by anthrotype** [comment]
Check how the fonttools subsetter prunes unused subroutines

**Comment by khaledhosny** [comment]
I tried, but couldn’t wrap my head around it from the first reading, will try again later :)

**Comment by khaledhosny** [comment]
I guess I don’t need to worry about this, it just how psautohint works, for now at least. We might need to rethink how we generate our OTFs at some point.

**Comment by khaledhosny** [comment]
That was my first thought, then I remembered that we don’t always process all glyphs (the user can select a subset of the glyphs to hint), so I’d need to always decode all the glyphs to find unused subroutines, which seems not to be worth it since current autohint output is suboptimal anyway and needs to be postprocessed, then one could as well handle unused subroutines there.
