### ISSUE TITLE
Report callbacks

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/psautohint#71]
The C library has a punch of callbacks and support code that was only used by `autohintexe`, namely the options:
```
   -ra Write alignment zones data. Does not hint or change glyph. Default extension is '.rpt'
   -rs Write stem widths data. Does not hint or change glyph. Default extension is '.rpt'
   -a Modifies -ra and -rs: Includes stems between curved lines: default is to omit these.
```

The `autohint` Python script (and consequently `psautohint`) does not expose any of these options. Any idea if they are still in use and how to test them?

**Comment by khaledhosny** [comment]
I should have checked AFDKO repo, they are used by `python/afdko/StemHist.py`. Do we need to have a similar script here?

**Comment by miguelsousa** [comment]
No, but don't remove the functionality from psautohint. When autohint gets replaced with psautohint, stemhist will shift to it as well.

**Comment by khaledhosny** [comment]
OK, the C Python extension will need to be updated to expose these callbacks as well.

**Comment by khaledhosny** [comment]
I have code in [wip/report-callbacks](https://github.com/adobe-type-tools/psautohint/tree/wip/report-callbacks) branch that hooks this up in Python extension and adds some tests. The tests crash under certain conditions due to what I believe are uninitialized global variables, but initializing these variables (which should be the right thing to do) breaks some of our existing tests, so either we were generating the wrong results all along or something else is not right.

**Comment by miguelsousa** [comment]
As described in https://github.com/adobe-type-tools/afdko/issues/210#issuecomment-412793284 the reports (`-ra`, `-rs`) issued by **autohintexe** (built from psautohint repo and afdko repo) contain differences that vary by platform.

**Comment by khaledhosny** [comment]
This is fixed now, will open a new issue for the test suite crashes.
