### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by madig** [adobe-type-tools/psautohint#77]
What are the major advancements since 1.1.0?

Also, might have wanted to call it 2.0.0 since the CLI was changed 😉

**Comment by miguelsousa** [comment]
> Also, might have wanted to call it 2.0.0 since the CLI was changed

A LOT of things changed. The first release was not really an official thing. Consider v1.7.0 the _de facto_ start of stability.

**Comment by madig** [comment]
Making 2.0.0 an even better idea 😉

**Comment by miguelsousa** [comment]
I disagree. We're saving 2.0.0 for the day when the codebase is fully clean and 90% covered.

**Comment by anthrotype** [comment]
I suggest you write the changes since last version directly in the annotated git tag message, they will show up in the Github releases as well.

**Comment by khaledhosny** [comment]
I’m adding ChangeLog to releases going forward. 1.7.0 should be seen as effectively the first public release.
