### ISSUE TITLE
Support Type 1 font formats

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/psautohint#81]
[fontTools can open PFAs](https://github.com/fonttools/fonttools/blob/master/NEWS.rst#22-released-2008-05-18), and judging from the [t1Lib tests](https://github.com/fonttools/fonttools/blob/master/Tests/t1Lib/t1Lib_test.py) it can open PFBs as well, so I expect it should be possible for `psautohint` to support Type 1 font formats via fontTools.

In `autohint` the support was implemented by making a call to **tx** to convert the Type 1 font to CFF:
```
tx -cff +b -std font.pfa font.cff
```

**Comment by khaledhosny** [comment]
I have been working on this in the past couple of days, just to find out that FontTools can only read Type 1 fonts, but after the font is parsed it can’t save it again and it has no way to compile the font data from its Python objects.

**Comment by khaledhosny** [comment]
At this point, I think it is easier to just check if `tx` is available and use it to convert the fonts, otherwise continue to raise an error.

**Comment by khaledhosny** [comment]
Or we can always save them as CFF fonts, if this is an acceptable compromise.
