### ISSUE TITLE
bez file spec doesn't say anything about

### ISSUE THREAD

**Issue by schriftgestalt** [adobe-type-tools/psautohint#86]
the `% ?? ??` after each hint  (e.g:`435 66 ry % 20 7`).

**Comment by miguelsousa** [comment]
@readroberts do you know the answer to this?

**Comment by khaledhosny** [comment]
Yes, this is only needed when doing MM hinting. If they are missing in the input bez string for reference master, the code will return and not copy any hints.

**Comment by skef** [comment]
Now that otfautohint is merged into afdko there's no active use of the bez format.
