### ISSUE TITLE
generated version.h causes problems for Debian build

### ISSUE THREAD

**Issue by jbicha** [adobe-type-tools/psautohint#98]
The generated `version.h` thing mentioned in #82 and #59 is making it difficult for me to build psautohint as a Debian package.

It looks like it wants me to add that `version.h` as a Debian patch but that seems annoying if someone will need to update that patch for every new release and it goes against the "don't change, don't track in version control" warning.

Respectfully, what problem are you trying to solve here?

```
dpkg-buildpackage: info: source package psautohint
dpkg-buildpackage: info: source version 1.7.0-1
dpkg-buildpackage: info: source distribution UNRELEASED
 dpkg-source --before-build psautohint-1.7.0
dpkg-buildpackage: info: host architecture amd64
 fakeroot debian/rules clean
dh clean --with python3 --buildsystem=pybuild
   dh_auto_clean -O--buildsystem=pybuild
I: pybuild base:217: python3.6 setup.py clean 
running clean
removing '/<<PKGBUILDDIR>>/.pybuild/cpython3_3.6/build' (and everything under it)
/usr/lib/python3/dist-packages/setuptools_scm/version.py:191: UserWarning: meta invoked without explicit configuration, will use defaults where required.
  "meta invoked without explicit configuration,"
'build/bdist.linux-amd64' does not exist -- can't clean it
'build/scripts-3.6' does not exist -- can't clean it
 dpkg-source -b psautohint-1.7.0
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building psautohint using existing ./psautohint_1.7.0.orig.tar.gz
dpkg-source: info: local changes detected, the modified files are:
 psautohint-1.7.0/libpsautohint/src/version.h
dpkg-source: error: aborting due to unexpected upstream changes, see /tmp/psautohint_1.7.0-1.diff.0HHSDa
dpkg-source: info: you can integrate the local changes with dpkg-source --commit
dpkg-buildpackage: error: dpkg-source -b psautohint-1.7.0 subprocess returned exit status 2
```

**Comment by anthrotype** [comment]
setuptools-scm is very popular among python projects. I suspect there are other Debian packages using it.
I’m not familiar with Debian packaging, sorry. 
Does this link help maybe?
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839687

**Comment by jbicha** [comment]
That bug report doesn't help much here.

I added [this patch](https://salsa.debian.org/fonts-team/psautohint/blob/debian/master/debian/patches/version.patch) to my Debian work-in-progress packaging for the new version but the patch feels problematic.

**Comment by khaledhosny** [comment]
Are you building from git check out or sdist archive? The archive should contain the generated `version.h` file.

**Comment by anthrotype** [comment]
yes, good point. The sdist does contain the autogenerated version.h (I just checked).

**Comment by anthrotype** [comment]
and there's also the `SETUPTOOLS_SCM_PRETEND_VERSION` environment variable to skip git altogether and set the version to an arbitrary string.
Anyway, I bet there are dozens of debian python packages using "the blessed package to manage your versions by scm tags". I don't think we are doing anything wrong on our side.

**Comment by jbicha** [comment]
I am using the .tar.gz from https://github.com/adobe-type-tools/psautohint/releases/tag/v1.7.0

Is there another place where I should be downloading from instead to have the pre-generated `version.h` ?

**Comment by anthrotype** [comment]
@khaledhosny maybe we should tag a new version and see if it fixes things downstream

@jbicha try to `python setup.py sdist` first from a fresh git clone, and then build from there. Does it work then?

**Comment by khaledhosny** [comment]
You can get it from PyPI: https://pypi.org/project/psautohint/#files, may be we should upload the sdist to GitHub releases as well.

**Comment by khaledhosny** [comment]
@anthrotype he is building 1.7.0, so I don’t think the problem he is seeing is affected by any of the recent changes.

**Comment by jbicha** [comment]
Yes, the 1.7.0 zip from pypi works. I think it would be useful if you would add that to the Github releases too but I can use pypi until that happens.

Feel free to close this bug when you're ready.
